name: test1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-175.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.0.8
  logger: ^2.5.0
  badges: ^3.1.2

  # Firebase dependencies
  image_picker: ^1.1.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^19.0.0
  firebase_analytics: ^11.4.3
  auto_route: ^10.0.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  firebase_app_check: ^0.3.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/
