// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr6er5WFidnNG9u60mNJuD2M53fXJ0_N8',
    appId: '1:293387036695:web:db923367849bfdcd84d452',
    messagingSenderId: '293387036695',
    projectId: 'test-714ac',
    authDomain: 'test-714ac.firebaseapp.com',
    databaseURL: 'https://test-714ac-default-rtdb.firebaseio.com',
    storageBucket: 'test-714ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGEyO84Z4EwLoDbJi9gXQ1K5bw-20Iyc',
    appId: '1:293387036695:android:58de2a055432ccf884d452',
    messagingSenderId: '293387036695',
    projectId: 'test-714ac',
    databaseURL: 'https://test-714ac-default-rtdb.firebaseio.com',
    storageBucket: 'test-714ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVRsrpomLE94OVjltmndK4uM6Jws8eE8Y',
    appId: '1:293387036695:ios:a0daf1d82f7ded0d84d452',
    messagingSenderId: '293387036695',
    projectId: 'test-714ac',
    databaseURL: 'https://test-714ac-default-rtdb.firebaseio.com',
    storageBucket: 'test-714ac.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVRsrpomLE94OVjltmndK4uM6Jws8eE8Y',
    appId: '1:293387036695:ios:a0daf1d82f7ded0d84d452',
    messagingSenderId: '293387036695',
    projectId: 'test-714ac',
    databaseURL: 'https://test-714ac-default-rtdb.firebaseio.com',
    storageBucket: 'test-714ac.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr6er5WFidnNG9u60mNJuD2M53fXJ0_N8',
    appId: '1:293387036695:web:650d1a40afc1145684d452',
    messagingSenderId: '293387036695',
    projectId: 'test-714ac',
    authDomain: 'test-714ac.firebaseapp.com',
    databaseURL: 'https://test-714ac-default-rtdb.firebaseio.com',
    storageBucket: 'test-714ac.firebasestorage.app',
  );
}
